version: '2'

services:
  web:
    build:
      context: .
    environment:
     - BUILD_ENV=dev
    ports:
     - 8080:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
